### ISSUE TITLE
Downloadpath incorrect

### ISSUE THREAD

**Issue by dolomiti70** [gooofy/zamia-ai#11]
The link to x86_64: http://goofy.zamia.org/repo-ai/centos/7/x86_64/ gives me an error.

**Comment by gooofy** [comment]
where did you find that URL?

**Comment by dolomiti70** [comment]
https://github.com/gooofy/zamia-ai direct under "Getting started"

**Comment by gooofy** [comment]
ah, missed that one. Thanks for letting me know - I have removed the outdated installation instructions now.
