### ISSUE TITLE
the problem of training data

### ISSUE THREAD

**Issue by thetimeofblack** [gooofy/zamia-ai#7]
I have found that the nlp_model want to drag the training data from sqlite but i have not found the source of the training data, could you tell me which file I can find about training data. Or show the process that training data is loaded into the database

**Comment by gooofy** [comment]
the training data is located in models/ - you can compile those by 

./ai_cli compile all

this should produce the sqlite db you're looking for

**Comment by thetimeofblack** [comment]
I have solved this problem, and I have run your program with the abandon of the kaldi model. And I find the data training takes me a lot of time. And the result remains uncertain with this data sets. So, my comprehension about the process is that you use seq2seq to translate the natural language into prolog language. Am I correct? So how to do with the wording embedding

**Comment by thetimeofblack** [comment]
I am a student in China, I am interested in the theory background of this project, hoping that you can give me some answers about my problem

**Comment by gooofy** [comment]
The time needed to train a model depends on your GPU, for my GTX 980 this process takes about 24 hours for the first 100k iterations (which seems enough for the current knowledge base). Alternatively, you can download pre-built models here: http://goofy.zamia.org/zamia-ai/ (in a few minutes actually, uploading as I am writing this).
About the word embedding: that is part of the model graph, i.e. an embedding layer is trained with the model. see zamiaai/seq2seq_model.py for details.

**Comment by thetimeofblack** [comment]
my GPU is P6000 , and after the change of GPU it runs faster

**Comment by gooofy** [comment]
very cool!
