### ISSUE TITLE
The summary

### ISSUE THREAD

**Issue by thetimeofblack** [gooofy/zamia-ai#8]
I have download your code and install on the computer with GPU P6000. After the experiment of my own module, I find the network lacks the capacity to handle the long sentence of seq2seq. So, I try to use your resource label to contain the long sentence to shrink the length. Could you give me the instruction about how to use the label like rdfsLabel(HUMAN, de, LABEL)

**Comment by gooofy** [comment]
Thanks for getting in touch again - glad to hear you got the basic code installed on your P6000 system :)

I am not sure what you mean by resource label to contain the long sentence to shrink the length? Are you trying to train your own seq2seq model here, maybe on a character-by-character basis? My approach was to break down the prolog code into bigger parts and create a dictionary over those parts.

In the upcoming Zamia-AI version (see the "swipl" branch) I am planning to go one step further and encode that whole subroutine that is called for handling any input sequence as one entry in the dictionary.

**Comment by thetimeofblack** [comment]
ok, I find you have created a data_engine to handle the interference with data_base and give the instruction for training_data. After my practice of my own topic, I find the machine get confused with the topic. It gives the answer from anther topic. Is there some thing wrong with seq2seq model or just I make mistakes about the training process ?

**Comment by gooofy** [comment]
You are right, Zamia AI getting stuck on topics was one of the main reasons (besides performance) for the recent redesign :) Please try again with the latest (python/xsb-prolog) based version, the problem should be fixed now (topics are no longer inputs to the neural network but are handled on the python/prolog side of things)
